/**
 * Privacy Policy page.
 */
export default function Privacy() {
  return (
    <div className="max-w-3xl mx-auto py-10 px-4 space-y-10">
      <div>
        <h1 className="text-white text-2xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-white/40 text-xs">Last updated: June 2026</p>
      </div>

      <Section title="What is collected">
        <p>
          Upon account creation, your first name, last name, email address, and a bcrypt
          hash of your password are stored. Your password is never stored as plaintext.
        </p>
        <p className="mt-3">
          Data submitted through the service is also stored: your Premier League
          final-standings predictions, any private leagues created or joined, and the
          scores generated by comparing predictions against the live table throughout
          the season.
        </p>
      </Section>

      <Section title="How it is used">
        <ul className="space-y-2 list-disc list-inside text-white/60 text-sm">
          <li>To authenticate users and keep sessions secure via short-lived JWT tokens.</li>
          <li>
            To send account verification codes and password-reset codes by email via
            SMTP. No marketing email is sent.
          </li>
          <li>To calculate and display scores within any leagues a user belongs to.</li>
          <li>To show aggregate platform statistics (total users, total predictions) on the homepage — these are anonymous counts only.</li>
        </ul>
      </Section>

      <Section title="Third parties">
        <p>
          No personal data is sold, rented, or shared with any third party.
        </p>
      </Section>

      <Section title="Data retention">
        <p>
          Account data and all associated records (predictions, league memberships,
          scores) are retained for as long as the account exists. Accounts can be deleted
          at any time from the Settings page, which permanently removes all associated data.
        </p>
      </Section>

      <Section title="Security">
        <p>
          Passwords are hashed with bcrypt before storage. Access tokens are short-lived
          JWTs. Verification and reset codes expire after 15 minutes and are single-use.
        </p>
      </Section>

      <Section title="Your rights">
        <p>
          Name, email, and password can be updated from the Settings page. Accounts can
          be deleted in full from the same page. To request a copy of your data, contact{' '}
          <a
            href="mailto:predict.the.ball.app@gmail.com"
            className="text-teal hover:text-teal-muted transition-colors"
          >
            predict.the.ball.app@gmail.com
          </a>
          .
        </p>
      </Section>

      <Section title="Cookies">
        <p>
          No tracking or advertising cookies are used. The only browser storage in use
          is <code className="text-teal/80 text-xs">localStorage</code> to hold the
          authentication token during a session.
        </p>
      </Section>

      <Section title="Changes">
        <p>
          Material changes to this policy will be reflected in the updated date at the
          top of this page. Continued use of the service after changes are posted
          constitutes acceptance of the revised policy.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions about this policy?{' '}
          <a
            href="mailto:predict.the.ball.app@gmail.com"
            className="text-teal hover:text-teal-muted transition-colors"
          >
            predict.the.ball.app@gmail.com
          </a>
        </p>
      </Section>
    </div>
  )
}

function Section({ title, children }) {
  return (
    <div className="bg-jet-dark rounded-2xl p-6 md:p-8">
      <h2 className="text-white font-semibold text-base mb-3">{title}</h2>
      <div className="text-white/60 text-sm leading-relaxed">
        {children}
      </div>
    </div>
  )
}
